openapi: 3.0.0
info:
  title: title
  termsOfService: 'https://test.test'
  contact:
    name: ggggg
    url: 'https://test.test'
    email: test@mail.com
  license:
    name: ''
  version: '1'
paths:
  '/api/data':
    post:
      tags:
        - Post data
      summary: Post data
      description: Post data
      operationId: post-data
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Status:
      title: Status
      type: string
      enum:
        - error-values
        - ACTIVE
